#!/bin/bash
set -e

. ../common

install_aur_package \
  google-chrome \
  google-cloud-sdk \
  beautysh \

  install_packages \
  atom \
  autopep8 \
  zim \
  vagrant \
  packer-io \
  shellcheck \
  php \
  composer  \
  ccache \
