#!/bin/bash
set -e

. ../common

install_aur_packages keybase-bin

install_packages \
  atom \
  autopep8 \
  beautysh \
  ccache \
  composer  \
  gitflow-avh \
  gitflow-bashcompletion-avh \
  google-chrome \
  google-cloud-sdk \
  packer-io \
  php \
  shellcheck \
  vagrant \
  zim \
