#!/bin/bash
set -e

. ../common

install_aur_packages keybase-bin

install_packages \
  google-chrome \
  google-cloud-sdk \
  beautysh \
  atom \
  autopep8 \
  zim \
  vagrant \
  packer-io \
  shellcheck \
  php \
  composer  \
  ccache \
