#!/bin/bash
set -e

. ../common

# Enable audio
install_packages pulseaudio
install_aur_package pulseaudio-ctl

# I am using Intel graphics on all my machines.
install_packages xf86-video-intel

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages xorg-server xorg-xrandr

# Install i3
install_packages i3-gaps compton xorg-xinit
install_aur_package j4-dmenu-desktop
install_aur_package polybar

install_packages tmux
install_packages mate-terminal

# Use autorandr to save/load monitor setups
# install_aur_package autorandr-git

# Download the wallpapers.
mkdir -p /usr/share/wallpapers/
curl --output /usr/share/wallpapers/frosted.jpg https://www.pknopf.com/wallpapers/frostedlights.jpg

# Install feh, which we will use to set the wallpaper.
install_aur_package feh

# Install
install_packages \
  firefox \
  lightdm \
  lightdm-gtk-greeter \
  lxterminal \
  xterm

# Enable services
systemctl enable lightdm.service
