#!/bin/bash
set -e

. ../common

# Enable audio
install_packages pulseaudio
install_aur_package pulseaudio-ctl

# I either use Intel graphics or Nvidia
install_packages \
xf86-video-intel \
nvidia \
nvidia-settings \
nvidia-utils \
opencl-nvidia \

# Touchpad Support
install_packages xf86-input-synaptics

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages xorg-server xorg-xrandr

# Install i3
install_packages i3-gaps compton xorg-xinit
install_aur_package j4-dmenu-desktop
install_aur_package polybar

# Install Terminal Emulators/Multiplexors
install_packages tmux
install_packages mate-terminal
install_aur_package kitty

# Use autorandr to save/load monitor setups
# install_aur_package autorandr-git

# Download the wallpapers.
mkdir -p /usr/share/wallpapers/
curl --output /usr/share/wallpapers/frosted.jpg https://www.pknopf.com/wallpapers/frostedlights.jpg
ln -s  /usr/share/wallpapers/frosted.jpg /usr/share/wallpapers/wallpaper.png

# Install feh, which we will use to set the wallpaper.
install_aur_package feh

# Install packages
install_packages \
  blueberry \
  dbus \
  dex \
  dmenu \
  firefox \
  lightdm \
  lightdm-gtk-greeter \
  lxterminal \
  python-dbus \
  thunar \
  xterm \
  zenity \


install_aur_package \
  dmenu-frecency-git \
  twmn-git \
  modprobed-db \
  ntfy-git \
  vmware-workstation12 \

# Enable services
systemctl enable lightdm.service
