#!/bin/bash
set -e

. ../common

# Enable audio
install_packages pulseaudio
install_packages pulseaudio-ctl

# I either use Intel graphics or Nvidia
install_packages \
  xf86-video-intel \
  nvidia \
  nvidia-settings \
  nvidia-utils \
  opencl-nvidia \

  # Touchpad Support
install_packages xf86-input-synaptics

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages xorg-server xorg-xrandr

# Install i3
install_packages i3-gaps compton xorg-xinit
# install_aur_packages j4-dmenu-desktop
install_packages polybar

# Install Terminal Emulators/Multiplexors
install_packages tmux
install_packages mate-terminal
install_packages kitty

# Use autorandr to save/load monitor setups
# install_aur_packages autorandr-git

# Download the wallpapers.
mkdir -p /usr/share/wallpapers/
curl --output /usr/share/wallpapers/frosted.jpg https://www.pknopf.com/wallpapers/frostedlights.jpg
ln -s  /usr/share/wallpapers/frosted.jpg /usr/share/wallpapers/wallpaper.png

# Install feh, which we will use to set the wallpaper.
install_packages feh

# Install packages
install_packages \
  blueberry \
  dbus \
  dex \
  dmenu \
  firefox \
  lightdm \
  lightdm-gtk-greeter \
  lxterminal \
  python-dbus \
  thunar \
  xterm \
  zenity \

# needed prior to install workstation12
GPG_KEY='702353E0F7E48EDB'
( gpg --keyserver ha.pool.sks-keyservers.net  --recv-keys "$GPG_KEY" || \
  gpg --keyserver pgp.mit.edu --recv-keys "$GPG_KEY" || \
  gpg --keyserver keyserver.pgp.com --recv-keys "$GPG_KEY" )
install_packages ncurses5-compat-libs
install_packages vmware-workstation12

install_packages \
  dmenu-frecency-git \
  twmn-git \
  modprobed-db \
  ntfy-git \

# Enable services
systemctl enable lightdm.service
