#!/bin/bash
set -e

. ../common

# Setup the locales.
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "password\npassword" | passwd
fi

# Use Bash
install_packages bash bash-completion

# Add our users
groupadd guests
useradd -m -G adm,ftp,games,http,log,rfkill,sys,systemd-journal,users,uucp,wheel -s /bin/bash dpendolino
# useradd -m -G guests,users -s /bin/zsh guest

# TODO: restrict access to su/sudo commands for non-wheel users

# Set the root password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd dpendolino
else
    echo "Using default user password..."
    echo -en "password\npassword" | passwd dpendolino
fi

# Install fresh copy of dotfiles for dpendolino.
# dotbot requires Python.
install_packages python
runuser -l dpendolino -c "git clone https://github.com/dpendolino/dotfiles.git ~/.dotfiles"
runuser -l dpendolino -c "cd ~/.dotfiles && ./install"
# Now that they are installed, removed dotbot to clean up the image.
runuser -l dpendolino -c "rm -r ~/.dotfiles/dotbot"

# Setup sudo
install_packages sudo
echo "dpendolino ALL=(ALL) ALL" >> /etc/sudoers

# Enable ssh
install_packages openssh
systemctl enable sshd

# Fonts
install_aur_package \
  nerd-fonts-complete \
  ttf-hack-powerline-git \
  ttf-google-fonts-git

install_packages \
  ttf-symbola \
  noto-fonts \
  noto-fonts-emoji \
  noto-fonts-extra \

# Locale
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "LC_COLLATE=en_US.UTF-8" >> /etc/locale.conf

# Timezone
rm /etc/localtime
ln -s ../usr/share/zoneinfo/US/Eastern /etc/localtime

# Time sync
install_packages ntp
systemctl enable ntpd

# Quality of life packages
install_packages \
fasd \
powerline \
python-pip \
cifs-utils \
archey3 \
vim

# Install custom PS1
pip install powerline-shell

# Install ZFS
cat >> /etc/pacman.conf << EndOfMessage
[archzfs]
Server = http://archzfs.com/\$repo/x86_64
EndOfMessage

# add archzfs keys
pacman-key --recv-keys 5E1ABF240EE7A126
pacman-key --lsign-key 5E1ABF240EE7A126

# Downgrade kernel to 14.15.1-2
cd /tmp
wget https://archive.archlinux.org/repos/month/core/os/x86_64/linux-4.14.15-1-x86_64.pkg.tar.xz
wget https://archive.archlinux.org/repos/month/core/os/x86_64/linux-headers-4.14.15-1-x86_64.pkg.tar.xz
pacman -U linux-4.14.15-1-x86_64.pkg.tar.xz linux-headers-4.14.15-1-x86_64.pkg.tar.xz

# update and install
pacman -Syy
install_packages spl-linux zfs-linux zfs-utils-common spl-utils-common
